# For more information see: https://github.com/denolib/setup-deno

name: ndjson-ci

on: [push, pull_request]

jobs:      
  test:
    runs-on: ${{ matrix.os }} # runs steps on each 'startegy.matrix.os'

    strategy:
      matrix:
        deno: ["1.13.2"]
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions
  
      - name: Setup Velociraptor
        run: "deno install -qAn vr https://deno.land/x/velociraptor@1.1.0/cli.ts"

      - name: Cache Dependencies
        if: matrix.os != 'macOS-latest'
        run: "deno cache deps.ts dev_deps.ts"

      - name: Check formatting
        if: matrix.os == 'ubuntu-latest'
        run: "vr fmt-check"

      - name: lint
        if: matrix.os == 'ubuntu-latest'
        run: "vr lint"
      
      - name: Run tests
        run: "vr test"
