# For more information see: https://github.com/denolib/setup-deno

name: ndjson-ci

on: [push, pull_request]

jobs:      
  test:
    runs-on: ${{ matrix.os }} # runs steps on each 'startegy.matrix.os'

    strategy:
      matrix:
        deno: ["1.5.4"]
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@c7d7968ad4a59c159a777f79adddad6872ee8d96
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions
  
      - name: Setup Velociraptor
        run: "deno install -qA -n vr https://deno.land/x/velociraptor@1.0.0-beta.16/cli.ts"

      - name: Setup env
        run: "echo ::add-path::$HOME/.deno/bin"

      - name: Cache Dependencies
        run: "deno cache deps.ts dev_deps.ts"

      - name: Check formatting
        if: matrix.os == 'ubuntu-latest'
        run: "vr fmt-check"

      - name: Run tests
        run: "vr test"
